### PR TITLE
tox-to-nox: support descriptions

### LINKED ISSUE #574: tox-to-nox: make docstring from testenv description
**How would this feature be useful?**
Session descriptions are useful for all the reasons they are currently supported by nox.

**Describe the solution you'd like**
It would be nice if tox-to-nox read testenv `description` field and turned it into a nox session docstring.

### PR DESCRIPTION
**Pull request by ktbarrett**
Closes #574. I didn't see any tox-to-nox tests, but it's a small enough change to manually confirm.

### CODE REVIEW

**Comment by FollowTheProcess** [comment]
There are tox-to-nox tests in `tests/test_tox_to_nox.py` they're all fairly simple "tox file in, nox file out" type tests, should be easy enough. If we're going to merge this in we'd need a test please, otherwise this looks great 👍🏻

**Comment by ktbarrett** [comment]
tox allows multiline string and folds them into a single line.

**Comment by FollowTheProcess** [comment]
> tox allows multiline string and folds them into a single line.

Cool! thanks

**Comment by FollowTheProcess** [comment]
@ktbarrett when you get a sec can you resolve the conflicts on this (it's just conflicting with your other change) and then we can get it merged in 👍🏻

**Review by FollowTheProcess — APPROVED** [review]

**Comment by FollowTheProcess** [comment]
Thanks @ktbarrett 🎉

**Pull request merged**
