### PR TITLE
Address #319: Give a create_tmp API

### PR DESCRIPTION
**Pull request by moshez**
This doesn't have docs or tests! Hooray :)

It does however show one way to implement it (kinda hacky) and a working use case for further discussion.

### CODE REVIEW

**Comment by moshez** [comment]
Hi @theacodes ! This is a rough draft, but I want some feedback on how much in the wrong direction am I going. Is it reasonable to assume the bin directory is writable? Should we push this API to the specific virtualenv? Is it OK to fail if bin is None? Etc.

**Comment by theacodes** [comment]
This looks like a great start.

> Is it reasonable to assume the bin directory is writable? 

Yup.

> Should we push this API to the specific virtualenv?

Nope, I think even "virtualenvless" sessions will have use cases for the tmpdir.

> Is it OK to fail if bin is None?

I think this should work even if there's no virtualenv for the session.

**Comment by moshez** [comment]
Hi @theacodes ! I added tests and documentation. I'm not sure if I understood your response to the third question -- do you mean I should have a tmpdir even without bin? In that case, I'm not sure the location would still make sense.

**Comment by theacodes** [comment]
>  do you mean I should have a tmpdir even without bin? In that case, I'm not sure the location would still make sense.

Yup.

I think it makes sense for it to go in `.nox/{session name}/tmp`.

**Comment by moshez** [comment]
OK, let me know what you think now. It should always work now.

**Comment by theacodes** [comment]
Looks good. 👌

**Comment by dhermes** [comment]
@moshez I'd love to chat about this feature and how it relates to my use / abuse of `.nox/libbezier-debug` and `.nox/libbezier-release` to cache and re-use debug and release builds of `libbezier` to speed up local dev for the Python parts of `bezier`: https://github.com/dhermes/bezier

**Comment by moshez** [comment]
@dhermes sent you an e-mail re: chatting about it. let me know!

**Pull request merged**
