### PR TITLE
Include changelog in documentation

### LINKED ISSUE #169: Include changelog in docs
**How would this feature be useful?**

Right now the changelog lives only in the repo.
Would be nice to have it in http://nox.thea.codes/en/stable/changelog.html where it's more visible.

We could just link from there to the file in the repo or convert the file from markdown to rst, so it would be rendered in the docs page.

### PR DESCRIPTION
**Pull request by theacodes**
Closes #169

### CODE REVIEW

**Comment by dhermes** [comment]
@theacodes I've put a lot of effort into making this "work right" for `bezier`: https://bezier.readthedocs.io/en/latest/releases/index.html

I'm happy to give `nox` the same treatment. WDYT? (It helps that I can maintain `latest.rst` in between releases and then just use the RST when creating the GitHub release.)

**Comment by theacodes** [comment]
I'm not opposed, but can you give me an idea of what we'd change?

**Comment by dhermes** [comment]
- Give each release it's own page
- Make sure the GH links render correctly in RTD as well as in GH
- Add a landing page for the changelog
- Add a `latest` doc that you can modify in between releases (this is "copying" what towncrier does but is lighter weight)

**Comment by theacodes** [comment]
Totally up to you. I'm fine either way.

**Pull request merged**
