### PR TITLE
ci: fix missing 3.8 -> 3.9 for CI

### PR DESCRIPTION
**Pull request by henryiii**
Followup to #528

### CODE REVIEW

**Comment by Tolker-KU** [comment]
Maybe not in scope here, but I wonder if we should give the lint and docs step the '--error-on-missing-interpreters' flag in CI to avoid this flying under the taser again?

**Comment by henryiii** [comment]
Do they need to be pinned to a specific Python, or could they just use the default?

**Comment by FollowTheProcess** [comment]
> Do they need to be pinned to a specific Python, or could they just use the default?

I've often thought this when running them locally and always having to use `--force-python` to run them. I always assumed there was a valid reason behind pinning these sessions?

If this is not the case, I think just using the default is the way to go 👍🏻

**Comment by FollowTheProcess** [comment]
> Maybe not in scope here, but I wonder if we should give the lint and docs steps the '--error-on-missing-interpreters' flag in CI to avoid this flying under the radar again?

This is a good idea if we cannot drop the pin for some compatibility reaason.

I've raised an issue #531 to track this, thanks for bringing it up (and quickly fixing it @henryiii !)

**Pull request merged**
