### PR TITLE
setup.py: Allow colorlog 4

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
I've packaged this up for openSUSE Tumbleweed, which is using colorlog 5, and the tests pass https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:python/python-nox

**Comment by jayvdb** [comment]
The Appveyor breakage looks unrelated - a bug in pip/conda/etc on Python 3.5.

**Comment by jayvdb** [comment]
Hmm.  Problem is also occurring on Windows py37 https://github.com/theacodes/nox/pull/258

**Comment by jayvdb** [comment]
@dhermes , no breakage here ;-)

**Comment by theacodes** [comment]
Rad, thanks for doing this and thank you @dhermes for taking a look. :)

**Pull request merged**
