### PR TITLE
docs: use myst-parser for md

### LINKED ISSUE #559: readthedocs broken
**Describe the bug**

The docs are broken, the "stable" release did not build after the recent release (missing from changelog), with:

```
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

See https://readthedocs.org/projects/nox/builds/

This should be fixable by setting a minimum version on some of the docs dependencies (why are those mixed with the test dependencies?) - readthedocs installs old versions of things by default, and then it's a no-op if you don't force an upgrade. Why they install a version of (something that uses HTML) that doesn't support Python 3.9+, I'm not sure, but forcing sphinx>=4 or something like that will likely fix the problem. Downgrading to Python 3.8 for the docs would fix it, too, but that's the wrong way to initially try to fix it.

I would highly recommend enabling PR readthedocs builds (in the readthedocs settings), they are very handy for catching bugs in the docs builds.

Also, it looks like "latest" hasn't built in a year or more, I'm guessing it was never changed to `main` from `master`, perhaps? It makes "latest" much older than "stable".

### PR DESCRIPTION
**Pull request by henryiii**
Closes #559 again.

See https://github.com/readthedocs/recommonmark/issues/221 - recommonmark has been sun-setted, myst-parser is the replacement.

### CODE REVIEW

**Comment by FollowTheProcess** [comment]
LGTM, might it be worth another PR build to check? @dhermes

**Comment by henryiii** [comment]
I think we were just merging then trying to rebuild readthedocs, since PR docs builds are not working. But this does work both locally and with the GHA docs build.

**Review by cjolowicz — APPROVED** [review]

**Comment by henryiii** [comment]
https://readthedocs.org/projects/nox/builds/15750719/ :D

**Comment by dhermes** [comment]
The point of `stable` is that it points at a **released** version of the code / docs. Not really sure what a good strategy is for that (short of cutting a release).

**Comment by henryiii** [comment]
I believe no changes have been made since the last release, so rebuilding with the current main would be identical to the last release. (As long as you don't leave it on current main).

**Comment by cjolowicz** [comment]
Another possibility would be to make a [post-release](https://www.python.org/dev/peps/pep-0440/#post-releases), `2022.1.7.post1`. That would trigger the stable build, and give us a PyPI release that's clearly marked as a minor correction without user-visible changes.

**Comment by henryiii** [comment]
Post releases should be metadata only (which is pretty much exactly what this is - docs), so that would also be fine. Though I'd still think that's a little overkill, the point of stable is to have docs for the latest release that don't also include features/changes added since the latest release, not that they have to be tied to an exact tag, but yes, it's fine.

**Comment by henryiii** [comment]
(In pybind11 we have a `stable` branch and that's what the `stable` docs builds from, which allows us to make docs fixes after a release if we really need to - thought usually we don't)

**Pull request merged**
