### PR TITLE
Allow providing a friendlier CLI name to sessions.

### PR DESCRIPTION
**Pull request by s0undt3ch**
```python
import nox

@nox.session
def a_bar(session):
    pass

@nox.session(name="not-a-bar")
def not_a_bar(session):
    pass
```

```
$ nox -l
Available sessions:
* a_bar
* not-a-bar
```

### CODE REVIEW

**Comment by stsewd** [comment]
I like this idea, maybe a test case with a name with spaces?

**Comment by s0undt3ch** [comment]
Sure.

**Comment by s0undt3ch** [comment]
Though, that's not CLI friendly, but that's besides your observation :smile:

**Comment by s0undt3ch** [comment]
Done.

**Comment by s0undt3ch** [comment]
So is this a go? Or a no go?

/cc @theacodes

**Comment by theacodes** [comment]
Looks good, but has conflicts, can you rebase?

**Comment by s0undt3ch** [comment]
Bummer. Sure.

**Comment by s0undt3ch** [comment]
Done.

**Comment by theacodes** [comment]
Thank you, thank you, @s0undt3ch! ✨

**Pull request merged**
