### PR TITLE
Update commands module

### PR DESCRIPTION
**Pull request by stsewd**
Drop some python 2 code and a typo in the docstring

### CODE REVIEW

**Comment by stsewd** [comment]
There is thi test

https://github.com/theacodes/nox/blob/bf4977d74d07e8630b2ee142bc59dcb4f2e319b9/tests/test_command.py#L42-L49

We don't expect byestrings objects in python3 I think, so we the test can be removed

**Comment by dhermes** [comment]
Looks like the failing test uses an explicit

```
{b"SIGIL": b"123"}
```

**Comment by stsewd** [comment]
@dhermes yeah, I think we are safe removing it, right?

**Comment by dhermes** [comment]
Yes seems reasonable

**Pull request merged**
